// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3XTj651_ZdifPVX60FcHeYAY7o60PVqM',
    appId: '1:550860627448:web:4e1db6871e8df1bed14a0d',
    messagingSenderId: '550860627448',
    projectId: 'news-app-backend-project',
    authDomain: 'news-app-backend-project.firebaseapp.com',
    storageBucket: 'news-app-backend-project.firebasestorage.app',
    measurementId: 'G-5HR8LP4DQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXi8tWM4-u895VfFWnKxMAsmIe-5dYuEk',
    appId: '1:550860627448:android:69eafbeb084ce95cd14a0d',
    messagingSenderId: '550860627448',
    projectId: 'news-app-backend-project',
    storageBucket: 'news-app-backend-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIcxyGomv9YJa9MbpNPHQo8NFw4wO8Noc',
    appId: '1:550860627448:ios:1f4c9cce1d7ff6dbd14a0d',
    messagingSenderId: '550860627448',
    projectId: 'news-app-backend-project',
    storageBucket: 'news-app-backend-project.firebasestorage.app',
    iosBundleId: 'com.example.newsAppBackendFunctionalities',
  );
}
